// Port Fastify server code from CODE/SERVER into a SvelteKit target folder.
// Generated trees (do not hand-edit): src/lib/service, src/lib/base, src/lib/controller,
// src/lib/kit_http.ts, src/types, src/routes/api
// Usage: node port_server_code.js <target-folder>

// -- IMPORTS

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// -- CONSTANTS

const scriptFilePath = fileURLToPath( import.meta.url );
const scriptFolderPath = path.dirname( scriptFilePath );
const codeFolderPath = path.resolve( scriptFolderPath, '..' );
const targetFolderArgument = process.argv[ 2 ];

if ( !targetFolderArgument )
{
    throw new Error( 'Usage: node port_server_code.js <target-folder>' );
}

const targetFolderPath = path.resolve( scriptFolderPath, targetFolderArgument );
const serverFolderPath = path.join( codeFolderPath, 'SERVER' );
const serverSourceFolderPath = path.join( serverFolderPath, 'src' );
const targetSourceFolderPath = path.join( targetFolderPath, 'src' );

const excludedControllerFileNameArray =
    [
        'image_upload_controller.ts'
    ];

// -- FUNCTIONS

function ensureFolder(
    folderPath
)
{
    fs.mkdirSync( folderPath, { recursive: true } );
}

// ~~

function copyFile(
    sourceFilePath,
    targetFilePath
)
{
    ensureFolder( path.dirname( targetFilePath ) );
    fs.copyFileSync( sourceFilePath, targetFilePath );
}

// ~~

function copyFolder(
    sourceFolderPath,
    targetFolderPath,
    shouldCopyFile = () => true
)
{
    if ( !fs.existsSync( sourceFolderPath ) )
    {
        return;
    }

    let entryArray = fs.readdirSync( sourceFolderPath, { withFileTypes: true } );

    for ( let entry of entryArray )
    {
        let sourceEntryPath = path.join( sourceFolderPath, entry.name );
        let targetEntryPath = path.join( targetFolderPath, entry.name );

        if ( entry.isDirectory() )
        {
            copyFolder( sourceEntryPath, targetEntryPath, shouldCopyFile );
        }
        else if ( shouldCopyFile( path.relative( sourceFolderPath, sourceEntryPath ), entry.name ) )
        {
            copyFile( sourceEntryPath, targetEntryPath );
        }
    }
}

// ~~

function readTextFile(
    filePath
)
{
    return fs.readFileSync( filePath, 'utf8' );
}

// ~~

function writeTextFile(
    filePath,
    fileContent
)
{
    ensureFolder( path.dirname( filePath ) );
    fs.writeFileSync( filePath, fileContent, 'utf8' );
}

// ~~

function transformControllerSource(
    sourceText
)
{
    let transformedText = sourceText;

    transformedText
        = transformedText.replace(
            /import type \{ FastifyReply, FastifyRequest \} from 'fastify';\r?\n/,
            "import type { KitReply, KitRequest } from '../kit_http';\n"
            );

    transformedText
        = transformedText.replace(
            /import type \{ FastifyRequest, FastifyReply \} from 'fastify';\r?\n/,
            "import type { KitReply, KitRequest } from '../kit_http';\n"
            );

    transformedText
        = transformedText.replace(
            /FastifyRequest<\{ Params: \{ id: string \} \}>/g,
            'KitRequest'
            );

    transformedText = transformedText.replace( /FastifyRequest/g, 'KitRequest' );
    transformedText = transformedText.replace( /FastifyReply/g, 'KitReply' );

    return transformedText;
}

// ~~

function transformSupabaseServiceSource(
    sourceText
)
{
    // CookieCapableReply already matches the Kit reply shim (setCookie / clearCookie).
    return sourceText;
}

// ~~

function writeKitHttpModule(
)
{
    let kitHttpSource
        = `// GENERATED by TOOL/port_server_code.js — do not hand-edit.

// -- IMPORTS

import type { Cookies, RequestEvent } from '@sveltejs/kit';

// -- TYPES

export type KitRequest =
    {
        params: Record<string, string>;
        cookies: Record<string, string | undefined>;
    };

// ~~

export type KitReply =
    {
        setCookie: (
            name: string,
            value: string,
            options?: Record<string, unknown>
        ) => void;
        clearCookie: (
            name: string,
            options?: Record<string, unknown>
        ) => void;
    };

// -- FUNCTIONS

export function getKitRequestFromEvent(
    event: RequestEvent
): KitRequest
{
    let cookieRecord: Record<string, string | undefined> = {};

    for ( let cookie of event.cookies.getAll() )
    {
        cookieRecord[ cookie.name ] = cookie.value;
    }

    let paramRecord: Record<string, string> = {};

    for ( let [ paramName, paramValue ] of Object.entries( event.params ) )
    {
        if ( paramValue !== undefined )
        {
            paramRecord[ paramName ] = paramValue;
        }
    }

    return (
        {
            params: paramRecord,
            cookies: cookieRecord
        }
        );
}

// ~~

export function getKitReplyFromCookies(
    cookies: Cookies
): KitReply
{
    return (
        {
            setCookie: (
                name: string,
                value: string,
                options?: Record<string, unknown>
            ): void =>
            {
                cookies.set(
                    name,
                    value,
                    {
                        path: '/',
                        ...( options ?? {} )
                    } as Parameters<Cookies['set']>[ 2 ]
                    );
            },
            clearCookie: (
                name: string,
                options?: Record<string, unknown>
            ): void =>
            {
                cookies.delete(
                    name,
                    {
                        path: '/',
                        ...( options ?? {} )
                    } as Parameters<Cookies['delete']>[ 1 ]
                    );
            }
        }
        );
}

// ~~

export function getKitHttpFromEvent(
    event: RequestEvent
):
    {
        request: KitRequest;
        reply: KitReply;
    }
{
    return (
        {
            request: getKitRequestFromEvent( event ),
            reply: getKitReplyFromCookies( event.cookies )
        }
        );
}
`;

    writeTextFile( path.join( targetSourceFolderPath, 'lib', 'kit_http.ts' ), kitHttpSource );
}

// ~~

function writeApiRouteFile(
    relativeRouteFolderPath,
    controllerImportPath,
    controllerClassName
)
{
    let routeFilePath
        = path.join(
            targetSourceFolderPath,
            'routes',
            'api',
            relativeRouteFolderPath,
            '+server.ts'
            );

    let routeSource
        = `// GENERATED by TOOL/port_server_code.js — do not hand-edit.

// -- IMPORTS

import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { ${ controllerClassName } } from '${ controllerImportPath }';
import { getKitHttpFromEvent } from '$lib/kit_http';

// -- VARIABLES

const pageController = new ${ controllerClassName }();

// -- FUNCTIONS

export const POST: RequestHandler = async (
    event
) =>
{
    let { request, reply } = getKitHttpFromEvent( event );

    return json( await pageController.processRequest( request, reply ) );
};
`;

    writeTextFile( routeFilePath, routeSource );
}

// ~~

function portControllerFolder(
)
{
    let sourceControllerFolderPath = path.join( serverSourceFolderPath, 'lib', 'controller' );
    let targetControllerFolderPath = path.join( targetSourceFolderPath, 'lib', 'controller' );

    ensureFolder( targetControllerFolderPath );

    if ( !fs.existsSync( sourceControllerFolderPath ) )
    {
        return;
    }

    let entryArray = fs.readdirSync( sourceControllerFolderPath, { withFileTypes: true } );

    for ( let entry of entryArray )
    {
        if ( !entry.isFile()
            || !entry.name.endsWith( '.ts' )
            || excludedControllerFileNameArray.includes( entry.name ) )
        {
            continue;
        }

        let sourceFilePath = path.join( sourceControllerFolderPath, entry.name );
        let targetFilePath = path.join( targetControllerFolderPath, entry.name );
        let sourceText = readTextFile( sourceFilePath );
        let transformedText = transformControllerSource( sourceText );

        writeTextFile( targetFilePath, transformedText );
    }
}

// ~~

function portServiceFolder(
)
{
    let sourceServiceFolderPath = path.join( serverSourceFolderPath, 'lib', 'service' );
    let targetServiceFolderPath = path.join( targetSourceFolderPath, 'lib', 'service' );

    ensureFolder( targetServiceFolderPath );

    if ( !fs.existsSync( sourceServiceFolderPath ) )
    {
        return;
    }

    let entryArray = fs.readdirSync( sourceServiceFolderPath, { withFileTypes: true } );

    for ( let entry of entryArray )
    {
        if ( !entry.isFile() || !entry.name.endsWith( '.ts' ) )
        {
            continue;
        }

        let sourceFilePath = path.join( sourceServiceFolderPath, entry.name );
        let targetFilePath = path.join( targetServiceFolderPath, entry.name );
        let sourceText = readTextFile( sourceFilePath );

        if ( entry.name === 'supabase_service.ts' )
        {
            sourceText = transformSupabaseServiceSource( sourceText );
        }

        writeTextFile( targetFilePath, sourceText );
    }
}

// ~~

function portServerCode(
)
{
    console.log( 'Porting server code from', serverFolderPath, 'to', targetFolderPath );

    if ( !fs.existsSync( serverSourceFolderPath ) )
    {
        throw new Error( `Server source folder not found: ${ serverSourceFolderPath }` );
    }

    let apiFolderPath = path.join( targetSourceFolderPath, 'routes', 'api' );

    if ( fs.existsSync( apiFolderPath ) )
    {
        fs.rmSync( apiFolderPath, { recursive: true, force: true } );
    }

    portServiceFolder();
    copyFolder(
        path.join( serverSourceFolderPath, 'lib', 'base' ),
        path.join( targetSourceFolderPath, 'lib', 'base' )
        );
    portControllerFolder();
    copyFolder(
        path.join( serverSourceFolderPath, 'types' ),
        path.join( targetSourceFolderPath, 'types' )
        );
    writeKitHttpModule();

    writeApiRouteFile(
        path.join( 'page', 'home' ),
        '$lib/controller/home_page_controller',
        'HomePageController'
        );
    writeApiRouteFile(
        path.join( 'page', 'properties' ),
        '$lib/controller/properties_page_controller',
        'PropertiesPageController'
        );
    writeApiRouteFile(
        path.join( 'page', 'property', '[id]' ),
        '$lib/controller/property_page_controller',
        'PropertyPageController'
        );

    let libIndexFilePath = path.join( targetSourceFolderPath, 'lib', 'index.ts' );

    if ( fs.existsSync( libIndexFilePath ) )
    {
        fs.unlinkSync( libIndexFilePath );
    }

    // Remove scaffold favicon asset folder if empty of meaning — keep assets if present
    console.log( 'Server port complete.' );
}

// -- STATEMENTS

portServerCode();
