<script lang="ts">
    // GENERATED by CODE/update_client_code.js — do not hand-edit.

    // -- IMPORTS

    import { page } from '$app/stores';
    import PageComponent from '$admin/lib/page/PropertyPage.svelte';

    // -- VARIABLES

    let { data } = $props();
</script>

<PageComponent id={ $page.params.id ?? '' } property={ data.property } languageCode={ data.languageCode } />
