FROM node:lts-alpine as builder

WORKDIR /app
COPY . .

WORKDIR /app/SERVER
RUN yarn install && yarn run build && rm -rf node_modules

WORKDIR /app/CLIENT
RUN yarn install && yarn run build && rm -rf node_modules

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/SERVER/dist .
COPY --from=builder /app/CLIENT/dist ./public

ENV HOST 0.0.0.0
ENV PORT 8000
ENV FUSION_PROJECT_DATABASE_HOST=db.xxx.supabase.co
ENV FUSION_PROJECT_DATABASE_PASSWORD=xxx
ENV FUSION_PROJECT_DATABASE_URL=https://xxx.supabase.co
ENV FUSION_PROJECT_DATABASE_KEY=xxx.xxx.xxx
ENV FUSION_PROJECT_STORAGE_URL=https://xxx.supabase.co/storage/v1/object/public

EXPOSE 8000

CMD ["node", "index.js"]
