<script lang="ts">
    // GENERATED by TOOL/update_client_code.js — do not hand-edit.

    // -- IMPORTS

    import PageComponent from '$admin/lib/page/PropertiesPage.svelte';

    // -- VARIABLES

    let { data } = $props();
</script>

<PageComponent propertyArray={ data.propertyArray } languageTag={ data.languageTag } />
