// GENERATED by CODE/port_server_code.js — do not hand-edit.

// -- IMPORTS

import type { Cookies, RequestEvent } from "@sveltejs/kit";

// -- TYPES

export type KitRequest =
    {
        params: Record<string, string>;
        cookies: Record<string, string | undefined>;
    };

// ~~

export type KitReply =
    {
        setCookie: (
            name: string,
            value: string,
            options?: Record<string, unknown>
        ) => void;
        clearCookie: (
            name: string,
            options?: Record<string, unknown>
        ) => void;
    };

// -- FUNCTIONS

export function getKitRequestFromEvent(
    event: RequestEvent
): KitRequest
{
    let cookieRecord: Record<string, string | undefined> = {};

    for ( let cookie of event.cookies.getAll() )
    {
        cookieRecord[ cookie.name ] = cookie.value;
    }

    let paramRecord: Record<string, string> = {};

    for ( let [ paramName, paramValue ] of Object.entries( event.params ) )
    {
        if ( paramValue !== undefined )
        {
            paramRecord[ paramName ] = paramValue;
        }
    }

    return (
        {
            params: paramRecord,
            cookies: cookieRecord
        }
        );
}

// ~~

export function getKitReplyFromCookies(
    cookies: Cookies
): KitReply
{
    return (
        {
            setCookie: (
                name: string,
                value: string,
                options?: Record<string, unknown>
            ): void =>
            {
                cookies.set(
                    name,
                    value,
                    {
                        path: "/",
                        ...( options ?? {} )
                    } as Parameters<Cookies["set"]>[ 2 ]
                    );
            },
            clearCookie: (
                name: string,
                options?: Record<string, unknown>
            ): void =>
            {
                cookies.delete(
                    name,
                    {
                        path: "/",
                        ...( options ?? {} )
                    } as Parameters<Cookies["delete"]>[ 1 ]
                    );
            }
        }
        );
}

// ~~

export function getKitHttpFromEvent(
    event: RequestEvent
):
    {
        request: KitRequest;
        reply: KitReply;
    }
{
    return (
        {
            request: getKitRequestFromEvent( event ),
            reply: getKitReplyFromCookies( event.cookies )
        }
        );
}
