// GENERATED by TOOL/update_client_code.js — do not hand-edit.

// -- IMPORTS

import type { PageServerLoad } from './$types';

// -- FUNCTIONS

export const load: PageServerLoad = async (
    {
        fetch,
        params
    }
) =>
{
    let apiPath = '/api/page/home';
    let response = await fetch(
        apiPath,
        {
            method: 'POST'
        }
        );

    if ( !response.ok )
    {
        throw new Error( `API request failed: ${ apiPath } (${ response.status })` );
    }

    return await response.json();
};
