<script lang="ts">
    // GENERATED by TOOL/update_client_code.js — do not hand-edit.

    // -- IMPORTS

    import PageComponent from '$admin/lib/page/HomePage.svelte';

    // -- VARIABLES

    let { data } = $props();
</script>

<PageComponent favoritePropertyArray={ data.favoritePropertyArray } languageTag={ data.languageTag } />
