// GENERATED by CODE/port_server_code.js — do not hand-edit.

// -- IMPORTS

import { json } from "@sveltejs/kit";
import type { RequestHandler } from './$types';
import { HomePageController } from '$lib/controller/home_page_controller';
import { getKitHttpFromEvent } from '$lib/kit_http';

// -- VARIABLES

const pageController = new HomePageController();

// -- FUNCTIONS

export const POST: RequestHandler = async (
    event
) =>
{
    let { request, reply } = getKitHttpFromEvent( event );

    return json( await pageController.processRequest( request, reply ) );
};
